repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # Use the latest version
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
  - repo: https://github.com/psf/black
    rev: 24.4.2  # Use the latest version
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the latest version
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0  # Use the latest version
    hooks:
      - id: flake8
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v1.10.1'  # Use the sha / tag you want to point at
#    hooks:
#      - id: mypy
#        args: [--strict, --ignore-missing-imports]
#        additional_dependencies: [tokenize-rt==3.2.0]
#  - repo: https://github.com/pytest-dev/pytest
#    rev: 6.2.4  # Use the latest version
#    hooks:
#      - id: pytest
#        name: pytest
#        entry: pytest
#        language: system
#        types: [python]
#        stages: [push]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9  # Use the latest version
    hooks:
      - id: bandit
        args: ["-r", "."]  # Recursively scan all files in the directory
